version: '3.8'
services:
  tictactoe:
    build: ./Heart.TicTacToe
    ports:
      - 5000:80
    volumes:
      - ./config/tictactoe.appsettings.json:/app/appsettings.json:ro
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433