version: '3'
services:
  auth:
    build: https://github.com/HeartofTheForce/Heart.Auth.git
    ports:
      - 5000:80
    volumes:
      - ./config/rsa_private.pem:/app/rsa_private.pem:ro
      - ./config/rsa_public.pem:/app/rsa_public.pem:ro

  tictactoe:
    build: https://github.com/HeartofTheForce/Heart.TicTacToe.git
    ports:
      - 5001:80
    volumes:
      - ./config/rsa_public.pem:/app/rsa_public.pem:ro
      
  tictactoe-client:
    depends_on:
      - auth
      - tictactoe
    build: https://github.com/HeartofTheForce/Heart.TicTacToe.Client.git#feature/init
    environment:
      - AUTH_URL=http://auth
      - TICTACTOE_URL=http://tictactoe

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
      - 443:443

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.0
    user: root
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./config/fields.yml:/usr/share/filebeat/fields.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro