filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    json.keys_under_root: false

setup.template.fields: "/usr/share/filebeat/fields.yml"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

processors:
  - add_docker_metadata: ~
  - copy_fields:
      fields:
        - from: "json.@mt"
          to: "message"
      ignore_missing: true
      fail_on_error: true
  - drop_event:
      when:
        or:
          - equals:
              container.image.name: "mcr.microsoft.com/mssql/server"
          - equals:
              container.image.name: "docker.elastic.co/kibana/kibana:7.8.0"
          - equals:
              container.image.name: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
          - equals:
              container.image.name: "docker.elastic.co/beats/filebeat:7.8.0"
