filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

processors:
  - add_docker_metadata: ~
  - decode_json_fields:
     fields: ["message"]
     target: "message_json"
  - drop_event:
      when:
        or:
          - equals:
              container.image.name : "docker.elastic.co/kibana/kibana:7.2.0"
          - equals:
              container.image.name : "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
          - equals:
              container.image.name : "docker.elastic.co/beats/filebeat:7.2.0"